plugins {
    id 'java'
    id 'application'
}

group = 'org.salvadanaio'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    // JUnit 5 per test
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.3'
}

test {
    useJUnitPlatform()
}

application {
    // Punto di ingresso principale
    mainClass = 'Main'
}
